version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    container_name: portfolio-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portfolio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
